version: '2'
services:
  arma-3-bots:
    image: "hasable/arma3-bots"
    container_name: "arma-3-bots"
    depends_on: 
        - arma-3-exile-database
    ports:
      - "2302:2302/udp" 
      - "2303:2303/udp" 
      - "2304:2304/udp"
      - "2305:2305/udp"
      - "2306:2306/udp"
      - "2309:2309/udp"
    environment:
      - EXILE_CONFIG_HOSTNAME=Exile+mods+bots DEV
      - EXILE_DATABASE_HOST=database
      - EXILE_DATABASE_NAME=altisdb
      - EXILE_DATABASE_USER=altisu
      - EXILE_DATABASE_PASS=altispw
      - ATK_CONFIG_ADMIN_LIST=76561197990024201,76561198007339024
    volumes:
      - /mnt/shares/logs:/opt/arma3/@ExileServer/extDB/logs/
    links:
        - "arma-3-exile-database:database"
  arma-3-exile-database:
    image: "mysql/mysql-server:5.7.19-1.1.1"
    container_name: "arma-3-exile-database"
    volumes:
      - database-content:/var/lib/mysql
      - /mnt/shares/mysql/logs:/var/log
    command: "--sql-mode=ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
volumes:
    database-content:
        external:
            name: database