version: '2'
services:
  arma-3-bots:
    image: "hasable/arma3-bots"
    container_name: "arma-3-bots-master"
    depends_on: 
      - arma-3-exile-database
    ports:
      - "2302:2302/udp" 
      - "2303:2303/udp" 
      - "2304:2304/udp"
      - "2305:2305/udp"
      - "2306:2306/udp"
      - "2309:2309/udp"
    environment:
      - EXILE_CONFIG_HOSTNAME=Exile+mods+bots DEV
      - EXILE_DATABASE_HOST=database
      - EXILE_DATABASE_NAME=altisdb
      - EXILE_DATABASE_USER=altisu
      - EXILE_DATABASE_PASS=altispw
      - ATK_CONFIG_ADMIN_LIST=76561197990024201,76561198007339024
      - HC_LIST=hc0,hc1
    volumes:
      - D:/mods/@CUP_UNITS-1.10.1:/opt/arma3/@CUPUnits
      - D:/mods/@CUP_UNITS-1.10.1/keys/cup_units-1.10.1.bikey:/opt/arma3/keys/cup_units-1.10.1.bikey
      - D:/mods/@CUP_VEHICLES-1.10.1:/opt/arma3/@CUPVehicles
      - D:/mods/@CUP_VEHICLES-1.10.1/keys/cup_vehicles-1.10.1.bikey:/opt/arma3/keys/cup_vehicles-1.10.1.bikey
      - D:/mods/@CUP_WEAPONS-1.10.1:/opt/arma3/@CUPWeapons
      - D:/mods/@CUP_WEAPONS-1.10.1/keys/cup_weapons-1.10.1.bikey:/opt/arma3/keys/cup_weapons-1.10.1.bikey
      - D:/mods/@R3F_ARMES-3.5.1:/opt/arma3/@R3FArmes
      - D:/mods/@R3F_ARMES-3.5.1/server_key/r3f.bikey:/opt/arma3/keys/r3fa.bikey
      - D:/mods/@R3F_UNITES-3.7.2:/opt/arma3/@R3FUnites
      - D:/mods/@R3F_UNITES-3.7.2/server_key/r3f.bikey:/opt/arma3/keys/r3fu.bikey
    networks:
      main:
        aliases:
          - arma-3-bots-master
          - master

  arma-3-bots-hc0:
    image: "hasable/arma3-bots"
    container_name: "arma-3-bots-hc0"
    environment:
      - HC_SERVER=master
    entrypoint: 
      - /usr/local/bin/docker-entrypoint-hc
    command: -mod=@Exile;@EBM;@A3XAI_HC;@CBA_A3;@CUPWeapons;@CUPUnits;@CUPVehicles;@R3FArmes;@R3FUnites -name=HC0
    volumes:
      - D:/mods/@CUP_UNITS-1.10.1:/opt/arma3/@CUPUnits
      - D:/mods/@CUP_UNITS-1.10.1/keys/cup_units-1.10.1.bikey:/opt/arma3/keys/cup_units-1.10.1.bikey
      - D:/mods/@CUP_VEHICLES-1.10.1:/opt/arma3/@CUPVehicles
      - D:/mods/@CUP_VEHICLES-1.10.1/keys/cup_vehicles-1.10.1.bikey:/opt/arma3/keys/cup_vehicles-1.10.1.bikey
      - D:/mods/@CUP_WEAPONS-1.10.1:/opt/arma3/@CUPWeapons
      - D:/mods/@CUP_WEAPONS-1.10.1/keys/cup_weapons-1.10.1.bikey:/opt/arma3/keys/cup_weapons-1.10.1.bikey
      - D:/mods/@R3F_ARMES-3.5.1:/opt/arma3/@R3FArmes
      - D:/mods/@R3F_ARMES-3.5.1/server_key/r3f.bikey:/opt/arma3/keys/r3fa.bikey
      - D:/mods/@R3F_UNITES-3.7.2:/opt/arma3/@R3FUnites
      - D:/mods/@R3F_UNITES-3.7.2/server_key/r3f.bikey:/opt/arma3/keys/r3fu.bikey
    links:
      - "arma-3-bots:master"
    networks:
      main:
        aliases:
          - arma-3-bots-hc0
          - hc0  

  arma-3-bots-hc1:
    image: "hasable/arma3-bots"
    container_name: "arma-3-bots-hc1"
    environment:
      - HC_SERVER=master
    entrypoint: 
      - /usr/local/bin/docker-entrypoint-hc
    command: -mod=@Exile;@EBM;@A3XAI_HC;@CBA_A3;@CUPWeapons;@CUPUnits;@CUPVehicles;@R3FArmes;@R3FUnites
    volumes:
      - D:/mods/@CUP_UNITS-1.10.1:/opt/arma3/@CUPUnits
      - D:/mods/@CUP_UNITS-1.10.1/keys/cup_units-1.10.1.bikey:/opt/arma3/keys/cup_units-1.10.1.bikey
      - D:/mods/@CUP_VEHICLES-1.10.1:/opt/arma3/@CUPVehicles
      - D:/mods/@CUP_VEHICLES-1.10.1/keys/cup_vehicles-1.10.1.bikey:/opt/arma3/keys/cup_vehicles-1.10.1.bikey
      - D:/mods/@CUP_WEAPONS-1.10.1:/opt/arma3/@CUPWeapons
      - D:/mods/@CUP_WEAPONS-1.10.1/keys/cup_weapons-1.10.1.bikey:/opt/arma3/keys/cup_weapons-1.10.1.bikey
      - D:/mods/@R3F_ARMES-3.5.1:/opt/arma3/@R3FArmes
      - D:/mods/@R3F_ARMES-3.5.1/server_key/r3f.bikey:/opt/arma3/keys/r3fa.bikey
      - D:/mods/@R3F_UNITES-3.7.2:/opt/arma3/@R3FUnites
      - D:/mods/@R3F_UNITES-3.7.2/server_key/r3f.bikey:/opt/arma3/keys/r3fu.bikey
    links:
      - "arma-3-bots:master"
    networks:
      main:
        aliases:
          - arma-3-bots-hc1
          - hc1
  
  arma-3-exile-database:
    image: "mysql/mysql-server:5.7.19-1.1.1"
    container_name: "arma-3-exile-database"
    volumes:
      - database-content:/var/lib/mysql
    command: "--sql-mode=ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    networks:
      main:
        aliases:
          - database

networks:
    main:

volumes:
    database-content:
        external:
            name: exile-database-content